# Site settings
title: Taylor J. Damann
email: tjdamann@wustl.edu
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD student in the Department of Political Science at Washington University in St. Louis.
  I study comparative politics and international relations.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://taydamann.com" # the base hostname & protocol for your site
twitter_username: taydamann
github_username:  taydamann
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
